name: omni check
on: [push, pull_request]

permissions:
  contents: read

jobs:
  omni-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lars20070/lat-check-action@v1
